Refactor condition
resource-hub-dev/rhub-api pull request #114
Opened 2022-06-14 15:32 UTC by thaorell

Refactor condition to this format
### Example
```
{
 msg: "error message",
 data: ['param_eq', 'foo', 'bar'],
}
```

This way, the UI and CLI do not have to render error messages and can output specific error message when condition fails

### Fixes

- [EXDRHUB-931](https://issues.redhat.com/browse/EXDRHUB-931)

### Checklist

- [X] OpenAPI file was updated
- [X] Run `tox`, no tests failed

2022-06-14 17:04 UTC, brhatiga requested changes

2022-06-14 17:04 UTC, brhatiga commented on src/openapi/lab.yml
>                example: ["and", ["param_eq", "extra_nic", true], ["param_gt", "num_nodes", 1]]
Update the example to include the msg property

2022-06-14 18:24 UTC, guioliveirabh approved these changes

2022-06-14 20:04 UTC, thaorell commented
@fpob do I have to create migration file as well?

2022-06-15 09:31 UTC, fpob approved these changes
> migration

no, db schema didn't change, parameters are stored as schemaless json

2022-06-15 12:27 UTC, merged