Improve logging
resource-hub-dev/rhub-api pull request #138
Opened 2022-08-02 13:25 UTC by fpob

### Fixes

- [EXDRHUB-1088](https://issues.redhat.com/browse/EXDRHUB-1088)

### Checklist

- [ ] Run `tox`, no tests failed

2022-08-02 14:12 UTC, freedgit commented
Since this has no changes to logging.*, I assume it still goes to stdout, right? Bc in that case we can just redirect everything to a centralized logger using fluent-bit, plain rsyslog via docker config etc

2022-08-02 14:21 UTC, fpob commented
@freedgit It depends how you have configured logging. By default (LOG_LEVEL env var), the logging output is console, but you can configure whatever you want in the config file (LOG_CONFIG env var) https://github.com/resource-hub-dev/rhub-api/blob/master/config/logging.example.yml

2022-08-02 19:27 UTC, brhatiga requested changes
LGTM, just a small spelling issue

2022-08-02 19:27 UTC, brhatiga commented on src/rhub/api/tower.py
> +            f'Re-aunching tower job {tower_job_data["id"]}',
Re-launching

2022-08-08 13:16 UTC, brhatiga approved these changes

2022-08-08 13:24 UTC, merged