Sphinx docs
resource-hub-dev/rhub-api pull request #36
Opened 2021-07-19 13:07 UTC by fpob

https://fpob-rhub-api.readthedocs.io/ (build from my fork)

2021-07-19 17:17 UTC, brhatiga requested changes
small spelling issue

2021-07-19 17:17 UTC, brhatiga commented on docs/releasenotes.rst
> +See `relases on GitHub <https://github.com/resource-hub-dev/rhub-api/releases>`_
"relases" change to "releases"

2021-08-02 19:53 UTC, brhatiga approved these changes
LGTM

2021-08-03 00:33 UTC, thaorell approved these changes

2021-08-03 09:05 UTC, merged