[WIP] Added fields for UI
resource-hub-dev/rhub-api pull request #45
Opened 2021-09-20 17:34 UTC by thaorell

## Description:
**Short summary:**
Adding some fields to the API and DB for UI information fetching. Please leave reviews

2021-09-20 17:52 UTC, brhatiga approved these changes

2021-09-21 08:31 UTC, fpob requested changes

2021-09-21 08:31 UTC, fpob commented on src/rhub/lab/model.py
> +        data['user_name'] = get_user(self.user_id)[0]['username']
You should use KeycloakClient directly

```
        data['user_name'] = get_keycloak().user_get(self.user_id)['username']
```

and similarly for groups.

API endpoint returns objects for use by the server (ConnexionResponse, Werkzeug response, ...), which doesn't make sense to use somewhere in the model.

2021-09-22 17:49 UTC, thaorell commented
Finally tests passed :1234:

2021-09-22 21:29 UTC, ivan-junior-rh approved these changes

2021-09-23 07:26 UTC, fpob approved these changes

2021-09-23 12:31 UTC, merged