DB migrations
resource-hub-dev/rhub-api pull request #79
Opened 2022-02-10 16:10 UTC by fpob

Migration tool / library is [alembic](https://alembic.sqlalchemy.org/en/latest/) and [flask-migrate](https://flask-migrate.readthedocs.io/en/latest/index.html) is a glue between alembic and flask, it adds CLI commands to flask, see `flask db --help`. Example how to use it is on flask-migrate page https://flask-migrate.readthedocs.io/en/latest/index.html#example

To make alembic work you need to delete DB and run `flask init`

---

... or if you are **100% sure you have latest DB schema** import

```sql
CREATE TABLE "alembic_version" (
    "version_num" character varying(32) NOT NULL,
    CONSTRAINT "alembic_version_pkc" PRIMARY KEY ("version_num")
) WITH (oids = false);
INSERT INTO "alembic_version" ("version_num") VALUES ('154ca1030fe2');
```

2022-02-15 15:20 UTC, brhatiga requested changes

2022-02-15 15:20 UTC, brhatiga commented on migrations/alembic.ini
> +# llogging is configured in `create_app`
/llogging/logging/s

2022-02-15 16:18 UTC, daniellutz commented
Besides the `llogging` misspell, everything else looks good to me.

2022-02-16 13:04 UTC, brhatiga approved these changes

2022-02-16 13:07 UTC, merged